name: sorioo
description: Sen Sorioo uzman cevapliyo.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  #state
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

  #networking
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1

  #routing
  go_router: ^8.0.5

  #local-data
  shared_preferences: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  google_sign_in: ^6.1.4
  
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  fpdart: ^0.6.0


  #utils
  gap: ^3.0.0
  iconly: ^1.0.1
  tap_builder: ^0.4.1
  pinput: ^2.2.31
  envied: ^0.3.0+3
  fluttertoast: ^8.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

  hive_generator: ^2.0.0
  
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1

  
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sorioo-launcher.png"
  remove_alpha_ios: true


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Satoshi-medium
      fonts:
        - asset: assets/fonts/Satoshi-Medium.ttf
    - family: Satoshi-Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.ttf
        
