name: sorioo
description: Sen Sorioo uzman cevapliyo.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  go_router: ^8.0.5
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  json_annotation: ^4.8.1
  pinput: ^2.2.31
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.2
  signalr_core: ^1.1.1
  tap_builder: ^0.4.1

dev_dependencies:
  build_runner: ^2.4.5

  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5

  hive_generator: ^2.0.0
  json_serializable: ^6.7.0

  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sorioo-launcher.png"
  remove_alpha_ios: true

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    - family: Satoshi-medium
      fonts:
        - asset: assets/fonts/Satoshi-Medium.ttf
    - family: Satoshi-Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.ttf
